learning about continue-on-error

diff --git a/.github/workflows/workflow_1.yml b/.github/workflows/workflow_1.yml
--- a/.github/workflows/workflow_1.yml
+++ b/.github/workflows/workflow_1.yml
@@ -1,44 +1,14 @@
 name: workflow_1
 on: push
 jobs:
-    lint:
-      runs-on: ubuntu-latest
-      steps:
-        - name: repo
-          uses: actions/checkout@v4
-        - name: install
-          run: npm ci
-        - name: lint
-          run: npm run lint
-    test:
-      needs: lint
-      runs-on: ubuntu-latest
-      steps:
-        - name: repo
-          uses: actions/checkout@v4
-        - name: install
-          run: npm ci
-        - name: test
-          run: npm run test
-    build:
-      needs: test
-      runs-on: ubuntu-latest
-      steps:
-        - name: repo
-          uses: actions/checkout@v4
-        - name: install
-          run: npm ci
-        - name: build
-          run: npm run build
-    deploy:
-      needs: build
-      runs-on: ubuntu-latest
-      steps:
-        - name: repo
-          uses: actions/checkout@v4
-        - name: install
-          run: npm ci
-        - name: deploy
-          run: echo "Deploy!!!"
-        
-
+	job1:
+		runs-on: ubuntu-latest
+		steps:
+			- name: step-1
+			  run: exit 1
+			  continue-on-error: true
+			- name: step-2
+			  run: echo "This is step-2"
+			- name: step-3
+			  if: failure()
+			  run: echo "step-1 is considered as failure"
